"""empty message

Revision ID: 836085426fc9
Revises: 
Create Date: 2018-12-28 20:40:12.461799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836085426fc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
